// Self-test harness: load a file of named reference tensors produced by a
// Python script, run our ops on the inputs, and compare against the expected
// outputs. M5 reuses this file format for the full-layer check.
//
// FTEN format (little-endian):
//   magic "FTEN" | count u32
//   per tensor: name_len u32, name bytes, n_dims u32, dims u64[n_dims]
//               (row-major shape), then f32 data

use crate::gguf::GgufFile;
use crate::model::{self, Config, Layer, Model};
use crate::tensor::{self, Tensor};
use anyhow::{bail, ensure, Context, Result};
use std::collections::HashMap;
use std::path::Path;

pub fn load_tensor_file(path: &Path) -> Result<HashMap<String, Tensor>> {
    let bytes = std::fs::read(path)
        .with_context(|| format!("cannot read {}", path.display()))?;
    let mut pos = 0;
    let take = |pos: &mut usize, n: usize| -> Result<&[u8]> {
        ensure!(*pos + n <= bytes.len(), "unexpected EOF at offset {}", *pos);
        let s = &bytes[*pos..*pos + n];
        *pos += n;
        Ok(s)
    };
    let read_u32 = |pos: &mut usize| -> Result<u32> {
        Ok(u32::from_le_bytes(take(pos, 4)?.try_into().unwrap()))
    };

    ensure!(take(&mut pos, 4)? == b"FTEN", "not an FTEN file");
    let count = read_u32(&mut pos)?;

    let mut tensors = HashMap::new();
    for _ in 0..count {
        let name_len = read_u32(&mut pos)? as usize;
        let name = String::from_utf8(take(&mut pos, name_len)?.to_vec())?;
        let n_dims = read_u32(&mut pos)? as usize;
        let mut shape = Vec::with_capacity(n_dims);
        for _ in 0..n_dims {
            shape.push(u64::from_le_bytes(take(&mut pos, 8)?.try_into().unwrap()) as usize);
        }
        let n: usize = shape.iter().product();
        let data: Vec<f32> = take(&mut pos, n * 4)?
            .chunks_exact(4)
            .map(|b| f32::from_le_bytes(b.try_into().unwrap()))
            .collect();
        tensors.insert(name, Tensor::from_vec(data, shape));
    }
    Ok(tensors)
}

/// Compare against a reference tensor; print one PASS/FAIL line and return
/// whether it passed.
pub fn check(name: &str, got: &Tensor, want: &Tensor, tol: f32) -> bool {
    if got.shape != want.shape {
        println!("FAIL {}: shape {:?}, expected {:?}", name, got.shape, want.shape);
        return false;
    }
    let max_diff = got
        .data
        .iter()
        .zip(&want.data)
        .map(|(g, w)| (g - w).abs())
        .fold(0.0f32, f32::max);
    let pass = max_diff.is_finite() && max_diff <= tol;
    println!(
        "{} {}: max abs diff {:.3e} (tol {:.0e})",
        if pass { "PASS" } else { "FAIL" },
        name,
        max_diff,
        tol
    );
    pass
}

/// M4: check matmul, rmsnorm, softmax, swiglu, add, mul against references
/// generated by scripts/check_m4.py.
pub fn run_m4(path: &Path) -> Result<()> {
    let t = load_tensor_file(path)?;
    let get = |name: &str| -> Result<&Tensor> {
        t.get(name).with_context(|| format!("reference file is missing '{}'", name))
    };
    let eps = get("eps")?.data[0];
    let tol = 1e-5;

    let mut all = true;
    all &= check("matmul", &tensor::matmul(get("a")?, get("w")?), get("matmul_out")?, tol);
    all &= check("rmsnorm", &tensor::rmsnorm(get("x")?, get("norm_w")?, eps), get("rmsnorm_out")?, tol);
    let mut sm = get("sm_in")?.clone();
    tensor::softmax(&mut sm);
    all &= check("softmax", &sm, get("softmax_out")?, tol);
    all &= check("swiglu", &tensor::swiglu(get("gate")?, get("up")?), get("swiglu_out")?, tol);
    all &= check("add", &tensor::add(get("x")?, get("b")?), get("add_out")?, tol);
    all &= check("mul", &tensor::mul(get("x")?, get("b")?), get("mul_out")?, tol);

    if !all {
        bail!("self-test failed");
    }
    println!("all ops match");
    Ok(())
}

/// M5: staged comparison of the block-0 forward pass against HF references
/// from scripts/check_m5.py. Stops at the first failing stage.
pub fn run_m5(model_path: &Path, ref_path: &Path) -> Result<()> {
    let refs = load_tensor_file(ref_path)?;
    let get = |name: &str| -> Result<&Tensor> {
        refs.get(name).with_context(|| format!("reference file is missing '{}'", name))
    };
    let tokens: Vec<u32> = get("tokens")?.data.iter().map(|&v| v as u32).collect();

    let file = GgufFile::open(model_path)?;
    let config = Config::from_gguf(&file)?;
    let layer = Layer::load(&file, 0)?;
    let embedding = Tensor::from_gguf(&file, "token_embd.weight")?;
    println!("config: {:?}", config);
    println!("tokens: {:?}", tokens);

    let stage = |n: u32, name: &str, got: &Tensor, want: &Tensor, tol: f32| -> Result<()> {
        ensure!(
            check(&format!("stage {} {}", n, name), got, want, tol),
            "stage {} ({}) failed; stop and debug before continuing",
            n,
            name
        );
        Ok(())
    };

    // stage 1: embedding lookup (also cross-validates dequant of the
    // largest tensor in the file)
    let x = model::embed(&embedding, &tokens);
    stage(1, "embeddings", &x, get("embeddings")?, 1e-6)?;

    // stage 2: input RMSNorm
    let xn = tensor::rmsnorm(&x, &layer.attn_norm, config.rms_eps);
    stage(2, "post_norm", &xn, get("post_norm")?, 1e-5)?;

    // stage 3: QKV projections with biases (validates matmul convention)
    let q = model::linear(&xn, &layer.wq, Some(&layer.bq));
    let k = model::linear(&xn, &layer.wk, Some(&layer.bk));
    let v = model::linear(&xn, &layer.wv, Some(&layer.bv));
    stage(3, "q_proj", &q, get("q_proj")?, 5e-5)?;
    stage(3, "k_proj", &k, get("k_proj")?, 5e-5)?;
    stage(3, "v_proj", &v, get("v_proj")?, 5e-5)?;

    // stage 4: RoPE (validates the half-split pairing convention)
    let mut q = q;
    let mut k = k;
    model::rope(&mut q, config.n_heads, config.head_dim, config.rope_theta);
    model::rope(&mut k, config.n_kv_heads, config.head_dim, config.rope_theta);
    stage(4, "q_rope", &q, get("q_rope")?, 5e-5)?;
    stage(4, "k_rope", &k, get("k_rope")?, 5e-5)?;

    // stage 5: attention probabilities (validates GQA mapping, scaling,
    // causal mask). Tolerance: logits are O(10) with ~1e-6 relative noise
    // inherited from stages 3-4; softmax maps that to ~3e-5 in the probs.
    // Structure (mask zeros, GQA routing) is pinned exactly by unit tests.
    let probs = model::attention_scores(&q, &k, config.n_heads, config.n_kv_heads, config.head_dim);
    stage(5, "attn_probs", &probs, get("attn_probs")?, 2e-4)?;

    // stage 6: the rest of the block, sub-step by sub-step for localization,
    // then the assembled layer_forward end to end
    let ctx = model::attention_apply(&probs, &v, config.n_heads, config.n_kv_heads, config.head_dim);
    stage(6, "attn_pre_o", &ctx, get("attn_pre_o")?, 2e-4)?;
    let attn = model::linear(&ctx, &layer.wo, None);
    stage(6, "attn_out", &attn, get("attn_out")?, 2e-4)?;
    let h1 = tensor::add(&x, &attn);
    stage(6, "resid1", &h1, get("resid1")?, 2e-4)?;
    let hn = tensor::rmsnorm(&h1, &layer.ffn_norm, config.rms_eps);
    stage(6, "post_attn_norm", &hn, get("post_attn_norm")?, 2e-4)?;
    let gate = model::linear(&hn, &layer.w_gate, None);
    let up = model::linear(&hn, &layer.w_up, None);
    stage(6, "ffn_gate", &gate, get("ffn_gate")?, 2e-4)?;
    stage(6, "ffn_up", &up, get("ffn_up")?, 2e-4)?;
    let ffn = model::linear(&tensor::swiglu(&gate, &up), &layer.w_down, None);
    stage(6, "ffn_out", &ffn, get("ffn_out")?, 2e-4)?;

    let block = model::layer_forward(&x, &layer, &config);
    stage(6, "block_out (layer_forward)", &block, get("block_out")?, 2e-4)?;

    println!("all stages green");
    Ok(())
}

/// M6 stage A: full 24-layer forward, last-position logits vs HF.
/// The logits tolerance is loose (24 layers of f32 accumulation) but the
/// argmax must match exactly and the top-5 ids must match in order.
pub fn run_m6(model_path: &Path, ref_path: &Path) -> Result<()> {
    let refs = load_tensor_file(ref_path)?;
    let get = |name: &str| -> Result<&Tensor> {
        refs.get(name).with_context(|| format!("reference file is missing '{}'", name))
    };
    let tokens: Vec<u32> = get("tokens")?.data.iter().map(|&v| v as u32).collect();
    let want = get("logits_last")?;

    let file = GgufFile::open(model_path)?;
    let t0 = std::time::Instant::now();
    let m = Model::load(&file)?;
    println!(
        "loaded {:.0} MB of f32 weights in {:.1} s",
        m.param_bytes() as f64 / (1024.0 * 1024.0),
        t0.elapsed().as_secs_f64()
    );

    let t0 = std::time::Instant::now();
    let logits = m.forward_last(&tokens);
    println!("forward over {} tokens took {:.2} s", tokens.len(), t0.elapsed().as_secs_f64());

    let ok = check("last-position logits", &logits, want, 5e-3);

    let top5 = |data: &[f32]| -> Vec<usize> {
        let mut idx: Vec<usize> = (0..data.len()).collect();
        idx.sort_by(|&a, &b| data[b].partial_cmp(&data[a]).unwrap());
        idx.truncate(5);
        idx
    };
    let ours = top5(&logits.data);
    let theirs = top5(&want.data);
    println!("our top-5:  {:?}", ours);
    println!("ref top-5:  {:?}", theirs);
    ensure!(ours[0] == theirs[0], "argmax differs: {} vs {}", ours[0], theirs[0]);
    ensure!(ours == theirs, "top-5 order differs");
    ensure!(ok, "logits diff exceeded tolerance");
    println!("argmax and top-5 match exactly");
    Ok(())
}
