// Self-test harness: load a file of named reference tensors produced by a
// Python script, run our ops on the inputs, and compare against the expected
// outputs. M5 reuses this file format for the full-layer check.
//
// FTEN format (little-endian):
//   magic "FTEN" | count u32
//   per tensor: name_len u32, name bytes, n_dims u32, dims u64[n_dims]
//               (row-major shape), then f32 data

use crate::tensor::{self, Tensor};
use anyhow::{bail, ensure, Context, Result};
use std::collections::HashMap;
use std::path::Path;

pub fn load_tensor_file(path: &Path) -> Result<HashMap<String, Tensor>> {
    let bytes = std::fs::read(path)
        .with_context(|| format!("cannot read {}", path.display()))?;
    let mut pos = 0;
    let take = |pos: &mut usize, n: usize| -> Result<&[u8]> {
        ensure!(*pos + n <= bytes.len(), "unexpected EOF at offset {}", *pos);
        let s = &bytes[*pos..*pos + n];
        *pos += n;
        Ok(s)
    };
    let read_u32 = |pos: &mut usize| -> Result<u32> {
        Ok(u32::from_le_bytes(take(pos, 4)?.try_into().unwrap()))
    };

    ensure!(take(&mut pos, 4)? == b"FTEN", "not an FTEN file");
    let count = read_u32(&mut pos)?;

    let mut tensors = HashMap::new();
    for _ in 0..count {
        let name_len = read_u32(&mut pos)? as usize;
        let name = String::from_utf8(take(&mut pos, name_len)?.to_vec())?;
        let n_dims = read_u32(&mut pos)? as usize;
        let mut shape = Vec::with_capacity(n_dims);
        for _ in 0..n_dims {
            shape.push(u64::from_le_bytes(take(&mut pos, 8)?.try_into().unwrap()) as usize);
        }
        let n: usize = shape.iter().product();
        let data: Vec<f32> = take(&mut pos, n * 4)?
            .chunks_exact(4)
            .map(|b| f32::from_le_bytes(b.try_into().unwrap()))
            .collect();
        tensors.insert(name, Tensor::from_vec(data, shape));
    }
    Ok(tensors)
}

/// Compare against a reference tensor; print one PASS/FAIL line and return
/// whether it passed.
pub fn check(name: &str, got: &Tensor, want: &Tensor, tol: f32) -> bool {
    if got.shape != want.shape {
        println!("FAIL {}: shape {:?}, expected {:?}", name, got.shape, want.shape);
        return false;
    }
    let max_diff = got
        .data
        .iter()
        .zip(&want.data)
        .map(|(g, w)| (g - w).abs())
        .fold(0.0f32, f32::max);
    let pass = max_diff.is_finite() && max_diff <= tol;
    println!(
        "{} {}: max abs diff {:.3e} (tol {:.0e})",
        if pass { "PASS" } else { "FAIL" },
        name,
        max_diff,
        tol
    );
    pass
}

/// M4: check matmul, rmsnorm, softmax, swiglu, add, mul against references
/// generated by scripts/check_m4.py.
pub fn run_m4(path: &Path) -> Result<()> {
    let t = load_tensor_file(path)?;
    let get = |name: &str| -> Result<&Tensor> {
        t.get(name).with_context(|| format!("reference file is missing '{}'", name))
    };
    let eps = get("eps")?.data[0];
    let tol = 1e-5;

    let mut all = true;
    all &= check("matmul", &tensor::matmul(get("a")?, get("w")?), get("matmul_out")?, tol);
    all &= check("rmsnorm", &tensor::rmsnorm(get("x")?, get("norm_w")?, eps), get("rmsnorm_out")?, tol);
    let mut sm = get("sm_in")?.clone();
    tensor::softmax(&mut sm);
    all &= check("softmax", &sm, get("softmax_out")?, tol);
    all &= check("swiglu", &tensor::swiglu(get("gate")?, get("up")?), get("swiglu_out")?, tol);
    all &= check("add", &tensor::add(get("x")?, get("b")?), get("add_out")?, tol);
    all &= check("mul", &tensor::mul(get("x")?, get("b")?), get("mul_out")?, tol);

    if !all {
        bail!("self-test failed");
    }
    println!("all ops match");
    Ok(())
}
